### ISSUE TITLE
Graphcool 1.0: New `graphcool.yml` format 

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#1328]
[Graphcool 1.0](https://github.com/graphcool/framework/issues/353) introduces many changes which requires some adjustments of the `graphcool.yml` format.

## What's new

* Local `.graphcoolrc` file is now part of `graphcool.yml` (`stages` instead of `targets`)
* `stages` are now pointing to the cluster the service should be deployed to
* Added `apikey` in favour of root tokens
* `datamodel` can be split up in multiple files #774 (formerly `types`)
* Added `migrations` which references YAML migration files #1263
* Renamed `functions` to `subscriptions` and restructured layout (removed `handler` level)
* Removed `permissions` & `authTokens`

## Full Example

```yml
service: my-demo-app

stages:
  default: dev
  dev: local
  staging: shared-eu-west-1
  prod: shared-eu-west-1

apikey: my-secret-apikey

datamodel:
- database/models.graphql
- database/enums.graphql

schema: schemas/database.graphql

migrations: database/migrations/

custom:
  serverlessEndpoint: 'https://bcdeaxokbj.execute-api.eu-west-1.amazonaws.com/dev'

subscriptions:
  userSignupEmail:
    query: database/subscriptions/user-signup.graphql
    webhook:
      url: ${self:custom.serverlessEndpoint}/user-signup
      headers:
        Authorization: ${env:MY_ENDPOINT_SECRET}
```

## Minimal example

```yml
service: my-demo-app

stages:
  dev: local

datamodel: database/types.graphql
```

In this example the following defaults are used:

* Missing `apikey`: No API key required to authenticate to the GraphQL API (not recommended)
* Missing `migrations`: By default looks for files matching this pattern `migrations/*.yml`
* Missing `schema`: See #1361
* Missing `subscriptions`: Optional
* Missing `custom`: Optional

### Merging `.graphcoolrc` and `graphcool.yml`

Unifying both file reduces the "file footprint" and therefore simplifies the getting started experience. 

You might argue that moving the `targets` section from the `.graphcoolrc` to the `graphcool.yml` is violating the [12 factor app principles](https://12factor.net/). While this is technically the case, it's very simple to get back the full separation if needed like in the following examples:

#### Using environment variables

```yml
targets:
  default: dev
  dev: ${env:GRAPHCOOL_TARGET_LOCAL}
  staging: ${env:GRAPHCOOL_TARGET_STAGING}
  prod: ${env:GRAPHCOOL_TARGET_PROD}
```

#### Using source file

```yml
targets: ${file(.graphcoolrc.yml):targets}
```

## Open questions

- [x] Should `migrations` point to a directory or to `*.yml` files via a globbing pattern?
  - decision: directory
- [x] This depends on #1329 
- [x] Should we already introduce a `version: 1` field (see [docker-compose](https://docs.docker.com/compose/compose-file/compose-versioning/))
  - decision: no, we can introduce `version: 2` field when we need it

**Comment by kbrandwijk** [comment]
- Putting targets in `graphcool.yml` forces you to manually reference an external file. I don't see any benefits of having targets in the same file, based on a normal workflow. You would normally not want to have these targets under source control. It simply doesn't work for local targets, and is inconvenient for shared cluster targets 
- Using different environment variables for different targets is still hard. I don't understand why this can't be made easier (using `dotenv` for example)
- The serverless endpoint for example, also has a stage (target) in it. So with multiple targets, this will introduce another set of environment variables, or the use of ${opt:stage}, which is not necessarily a 1-on-1 match
- Migrations are linked to a deployment, not to the service definition itself. It's the migration from one version to the next, but there's no version concept. I don't think migrations belong in the service definition
- Disconnecting the service name from the stage (e.g. allowing the same service name for multiple stages) should make configuration a lot easier. Like serverless, you would have just one service name, and it can be deployed to multiple stages and clusters. This would be far more straightforward
- If `rootTokens` are removed, then how do you set/retrieve the rootToken to connect to the endpoint?
- If targets are pointing to service names, and endpoints are still using service id's, that means that it's no longer possible to know the endpoint address by just looking at .graphcoolrc, you would need to run `gc info`. This is a very common task, that should be as easy as possible. Unless you are also going to use service names for API endpoints, then this is not an issue.

**Comment by kbrandwijk** [comment]
The proposal in #1329 might affect the `graphcool.yml` structure, as it proposes to add `service name` to this file, as well as defaults for stage, cluster and region.

**Comment by schickling** [comment]
Thanks a lot for your great suggestions @kbrandwijk. Following your proposal here is what the `graphcool.yml` file would look like:

```yml
service: my-demo-app

stages:
  default: dev
  dev: local
  staging: shared-eu-west-1
  prod: shared-eu-west-1

types:
- database/models.graphql
- database/enums.graphql

migrations: database/migrations/*.yml 

custom:
  serverlessEndpoint: 'https://bcdeaxokbj.execute-api.eu-west-1.amazonaws.com/dev'

subscriptions:
  userSignupEmail:
    query: database/subscriptions/user-signup.graphql
    webhook:
      url: ${self:custom.serverlessEndpoint}/user-signup
      headers:
        Authorization: ${env:MY_ENDPOINT_SECRET}
```

**Comment by kbrandwijk** [comment]
Maybe cluster and regions (shared-eu-west-1) should be split, but that depends on what happens with #1329. This is more like Serverless:
```
service: my-demo-app
defaults:
  stage: dev
  cluster: shared
  region: eu-west-1

stages:
  dev: local #shorthand notation
  test:
    region: us-east-2

types:
- database/models.graphql
- database/enums.graphql

migrations: database/migrations/*.yml 

custom:
  serverlessEndpoint: 'https://bcdeaxokbj.execute-api.eu-west-1.amazonaws.com/dev'

subscriptions:
  userSignupEmail:
    query: database/subscriptions/user-signup.graphql
    webhook:
      url: ${self:custom.serverlessEndpoint}/user-signup
      headers:
        Authorization: ${env:MY_ENDPOINT_SECRET}
```

You only specify the defaults once, and only specify the overrides for the stages.

**Comment by sorenbs** [comment]
@schickling - Is the final decision that `default` is a special key in the stages map?

```yml
stages:
  default: dev
  dev: local
  staging: shared-eu-west-1
  prod: shared-eu-west-1
```

**Comment by sorenbs** [comment]
Two considerations:

- It should be possible to specify a different apiKey for different stages.
- It should be possible to rotate apiKey without any applications using it loosing access. This requires support for multiple active apiKeys
- The apiKey should not be in transit between application and graphcool. Instead it should be used to sign a jwt. Hence I suggest we rename it to secret.
- It should be highly discouraged to write secrets directly in graphcool.yml as this will be checked into git.

I suggest the following format:

```yml
service: my-demo-app

stages:
  default: dev
  dev: 
    cluster: local
    secrets:
      - ${loaded from .env file}
  staging: 
    cluster: shared-eu-west-1
    secrets:
      - ${loaded from .env file}
  prod: 
    cluster: shared-eu-west-1
    secrets:
      - ${loaded from .env file}
``` 

Additionally I suggest that `graphcool init` creates a .env file with a cryptographically secure secret.

**Comment by kbrandwijk** [comment]
I like the `secret` approach. That will also close https://github.com/graphcool/framework/issues/362 as part of this proposal.

**Comment by sorenbs** [comment]
Thanks @kbrandwijk! 

Do you see any issue in allowing the secret to be set directly in `graphcool.yml`? 
I'm concerned that people might accidentally commit secrets to source control, but I think we can alleviate that issue somehow by always referencing .env in examples and files generated by the cli.

**Comment by kbrandwijk** [comment]
@sorenbs I don't think you need to enforce that. Educate people to follow best practices, after that, it's up to them.

**Comment by sorenbs** [comment]
@schickling new Minimal example:

```
service: my-demo-app

stages:
  dev:
    cluster: local
    secrets: mySecret

datamodel: database/types.graphql
```

**Comment by sorenbs** [comment]
After much deliberation with @schickling we came to a new proposal. The main points driving this proposal are:

- We prefer to keep the stages field simple

```yml
service: my-demo-app

secrets: "${env:GRAPHCOOL_SECRETS}"
disableAuth: ${env:DISABLE_GRAPHCOOL_AUTH}

stages:
  dev: local

datamodel: database/types.graphql
```

### Environment Variables

The Graphcool CLI will load environment variables from three places in the following order:

- the local environment
- a .env file specified with the `--dotenv` parameter
- a .env file in the same directory if no `--dotenv` parameter is specified

If the `secrets` field is not present or it is empty, the CLI will return an error unless `disableAuth` is set to true.

### Simple Example

In a simple case where the developer want to run the service locally without auth and be able to deploy to production from their local machine, the setup could look like this:

#### graphcool.yml
```yml
service: my-demo-app

secrets: "${env:GRAPHCOOL_SECRETS}"
disableAuth: ${env:DISABLE_GRAPHCOOL_AUTH}

stages:
  default: dev
  dev: local
  prod: london-cluster

datamodel: database/types.graphql
```

#### .env

This is the env configuration for local development

```
DISABLE_GRAPHCOOL_AUTH=true
```

#### .env.prod

This is the env configuration for production

```
GRAPHCOOL_SECRETS=secret-1, secret-2
```

#### Deploying the service

Deploying to local dev:

```sh
graphcool deploy
```

Deploying to production:

```sh
graphcool deploy --stage prod --env .env.prod
```

## Open Questions

- [ ] Should we automatically load `.env` file if present? [now](https://zeit.co/docs/features/env-and-secrets) requires explicit loading by using the argument `--dotenv=true`
- [ ] Should we support passing env arguments directly like this `-e GRAPHCOOL_SECRETS="secret-1, secret-2"`?
