### ISSUE TITLE
Global config migration strategy & format: `~/.graphcoolrc`

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#1474]
Example config:

```yml
graphcool-framework:
  platformToken: 'xxx'

graphcool-1.0:
  cloudSessionKey: 'xxx'

  clusters:
    local:
      host: 'http://localhost:60000'
      secret: 'xxx'
```
