### ISSUE TITLE
Seeding parameter is interpreted relative to `deploy` command, not relative to `graphcool.yml` file

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#1557]
**The file path for `seed: import: seed.graphql` should be seen relative to `graphcool.yml` instead of relative to the working directory of `graphcool deploy`.**

---

My file tree:

```sh
.
├── .graphqlconfig.yml
├── database
│   ├── datamodel.graphql
│   ├── graphcool.yml
│   └── seed.graphql
└── src
    ├── generated
    │   └── graphcool.graphql
    └── schema.graphql
```

My `graphcool.yml` file (not working):

```yml
# the name for the service (will be part of the service's HTTP endpoint)
service: ts-seed3

# the cluster and stage the service is deployed to
stage: dev

# to disable authentication:
# disableAuth: true
secret: mysecret123

# the file path pointing to your data model
datamodel: datamodel.graphql

# seeding your service with initial data
seed: 
  import: seed.graphql

cluster: local
```

When I deploy with the above `graphcool.yml` file, this is the output:

```sh
Creating stage dev for service ts-seed4 ✔
Deploying service `ts-seed4` to stage `dev` on cluster `local` 62ms

Changes:

  Post (Type)
  + Created type `Post`
  + Created field `id` of type `GraphQLID!`
  + Created field `isPublished` of type `Boolean!`
  + Created field `title` of type `String!`
  + Created field `text` of type `String!`
  + Created field `updatedAt` of type `DateTime!`
  + Created field `createdAt` of type `DateTime!`

Applying changes 1.1s

Hooks:

Importing seed dataset from `seed.graphql` !
 ▸    Path seed.graphql does not exist

Get in touch if you need help: https://www.graph.cool/forum
To get more detailed output, run $ set -x DEBUG "*"
```

My `graphcool.yml` file (working):

```diff
# the name for the service (will be part of the service's HTTP endpoint)
service: ts-seed3

# the cluster and stage the service is deployed to
stage: dev

# to disable authentication:
# disableAuth: true
secret: mysecret123

# the file path pointing to your data model
datamodel: datamodel.graphql

# seeding your service with initial data
seed: 
-  import: seed.graphql
+  import: database/seed.graphql

cluster: local
```
