### ISSUE TITLE
False positive ? : Relations are currently not supported

### ISSUE THREAD

**Issue by omatrot** [graphcool/graphcool#1589]
**Current behavior**
Trying to deploy a service with the following:
hello.graphql
```
type HelloPayload {
  results: Json!
}

extend type Query {
  hello(email: string!
    password: string!
    startDate: DateTime!
    duration: int!): HelloPayload
}
```
graphcool.yml

```
# In the types.graphql you define your data schema
types: ./types.graphql


functions:
  hello:
    handler:
      code: src/hello.ts
    type: resolver
    schema: src/hello.graphql

permissions:
  - operation: "*"

```

types.graphql

```
# The following types define the data model of the example service
# based on which the GraphQL API is generated
```
.ts file

```
import { FunctionEvent } from '../node_modules/graphcool-lib';

interface EventData {
    email: string
    password: string
    startDate: Date
    duration: number
}

export default async (event: FunctionEvent<EventData>) => {
    await new Promise(r => setTimeout(r, 50));

    return { response: event.data.email };
}
```

Output og GraphCool Deploy:

```
graphcool-framework deploy

? Please choose the cluster you want to deploy to

shared-eu-west-1

? Please choose the target name test
Creating service roomsavailability in cluster shared-eu-west-1... ✔
Bundling functions... 4.5s
Deploying... 659ms
There are issues with the new service definition:

  Global
    ✖ Schema Extension Error for function 'hello': Relations are currently not supported. Field 'email'

```

What is wrong with the field email ? AFAIK it is not a relation...

**Expected behavior?**

Service is created.
