### ISSUE TITLE
Include context for functions

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#219]
- authenticated header or user id 
- project id
- custom "environment variables"

**Comment by enricenrich** [comment]
+1 on this 👍🙌

**Comment by joarwilk** [comment]
Oh god yes

**Comment by thenikso** [comment]
I would add a function to query the current graph.cool api as well?

**Comment by CameronK** [comment]
+1 to @thenikso. It would be really powerful to define a query that is sent by the "Data write" step to the next step (essentially, in the same position as TRANSFORM_PAYLOAD).

**Comment by kbrandwijk** [comment]
I would suggest a uniform approach to custom mutations (so a event.context.graphcool object with projectId and PAT)

**Comment by mattfysh** [comment]
This sounds like something that might be easy to add to beta testing? If you guys are running on AWS lambda, the context object contains a few things that would be useful within a function.

The project ID/alias would also be great for porting the function across multiple environments, for now I'm hard coding the value and updating as I promote functions across environments

**Comment by joarwilk** [comment]
This issue currently blocks using `graphcool-lib` on AWS Lambda, since it relies on the `context.graphcool` object.

**Comment by marktani** [comment]
Hey @joarwilk, you can manually construct the needed context as I showed in [a recent answer in the Forum](https://www.graph.cool/forum/t/query-separate-table-during-pipeline/415/2?u=nilan) 🙂

**Comment by kbrandwijk** [comment]
Please also include project region in the context information. The use case for this is that some third party API's (like Azure) have regions too, and it would be nice to automatically use the project region for those.

**Comment by kbrandwijk** [comment]
Fixed?

**Comment by mattfysh** [comment]
I had this issue a couple of days ago, `fromEvent` from `graphcool-lib` was working for Schema Extensions, but not for Request Pipeline functions. @sorenbs has this fix been released?

**Comment by kbrandwijk** [comment]
It seems projectId and PAT are now also available for RP hooks, but not authentication data...

**Comment by sorenbs** [comment]
Sorry about the confusion. We are currently consolidating our internal and external issue trackers and that got me tripped up. I closed this issue prematurely.

Previously subscriptions and request pipeline functions did not have a context object. They now have a context that is partially correct, including the pat and projectId.

Please be aware that we will make a decision on https://github.com/graphcool/graphcool/issues/460 shortly, and that might require you to specifically configure a pat to be available in the context. Please also note that we are in the process of renaming pat to rootToken.

In short - i'll reopen this ticket for now :-)

**Comment by marktani** [comment]
We'll also need to take https://github.com/graphcool/graphcool/issues/460 in account.

**Comment by sorenbs** [comment]
All functions will have the following context:

```js
{
  auth: {
    typeName
    nodeId
    token
  },
  graphcool: {
    projectId
    alias
    pat # this will be deprecated shortly, use rootToken instead
    rootToken
  }
}
```

By default, `rootToken` will contain a `Temporary Root Token` that is valid for 5 minutes. 

> See https://github.com/graphcool/graphcool/issues/740 for token terminology

For a given function you can configure a named `Root Token` to be injected instead of a `Temporary Root Token` or you can choose to not inject a `Root Token` at all:

## Inject named Root Token

This configuration injects the `Root Token` with the name `authenticate`: 

```
functions:
  authenticteCustomer:
    handler:
      code:
        src: ./code/authenticate.js
    context:
      rootToken: authenticate
    type: schemaExtension
    schema: ./code/authenticate.graphql

rootTokens:
- authenticate
```

> Note: In the future it will be possible to control the scope of a Root Token. This feature will make it more relevant to use a named Root Token

## No Root Token

This configuration disables Root Token injection:

```
functions:
  authenticteCustomer:
    handler:
      code:
        src: ./code/authenticate.js
    context:
      rootToken: null
    type: schemaExtension
    schema: ./code/authenticate.graphql

rootTokens:
- authenticate
```

> Note: In the future we might make it possible to configure the default behaviour for root token injection.
