### ISSUE TITLE
graphcool-cli does not get content of function handlers

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#449]
<a href="https://github.com/danmkent"><img src="https://avatars2.githubusercontent.com/u/21933206?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [danmkent](https://github.com/danmkent)**
_Wednesday Sep 06, 2017 at 14:51 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/254_

----

**What is the current behavior?**

When using graphcool-cli version `1.3.8`, doing a `graphcool pull` gets a `graphcool.yml` file that is missing the code for function handlers:

```
functions:
  add:
    handler: {}
    type: schemaExtension
  CheckVersion:
    handler: {}
    type: operationBefore
    operation: Versioned.update
  TestJson:
    handler: {}
    type: schemaExtension
```

**What is the expected behavior?**

Code for function handlers is included, either directly or with a reference to a separate file (like what happens for permissions queries)
