### ISSUE TITLE
automatically inject shortlived (5 minutes) pat in all functions context

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#460]
<a href="https://github.com/sorenbs"><img src="https://avatars3.githubusercontent.com/u/281337?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sorenbs](https://github.com/sorenbs)**
_Thursday Sep 07, 2017 at 17:30 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/265_

----

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Thursday Sep 07, 2017 at 17:36 GMT_

----

That doesn't play well with the FR to have more control over the permissions given to a PAT...

**Comment by schickling** [comment]
<a href="https://github.com/sorenbs"><img src="https://avatars3.githubusercontent.com/u/281337?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sorenbs](https://github.com/sorenbs)**
_Thursday Sep 07, 2017 at 18:47 GMT_

----

That's correct @kbrandwijk 

We need a mechanism to specify the pat given to a function context. What do you think of something like this?

```yaml
functions:
  authenticteCustomer:
    handler:
      code:
        src: ./code/authenticate.js
    context:
      rootToken: authenticate
    type: schemaExtension
    schema: ./code/authenticate.graphql

rootTokens:
- authenticate
```
