### ISSUE TITLE
support wildcard permissions

### ISSUE THREAD

**Issue by sorenbs** [graphcool/graphcool#521]
suggested syntax:

```
permissions:
  - operation: *
  - operation: User.*
  - operation: SomeRelation.*
```

New projects should have a single wildcard permission:

```
permissions:
  - operation: *
```

This makes it more palatable to implement https://github.com/graphcool/graphcool/issues/459
