### ISSUE TITLE
Function handler definition shortcuts

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#529]
Writing function handler definitions can get very verbose as in the following example:

``` 
functions:
  hello:
    handler:
      code:
        src: ./src/hello.js
```

I'm proposing the following shortcuts:

### 1. Allow file path as string value for `code`

``` 
functions:
  hello:
    handler:
      code: ./src/hello.js
```

### 2. Use code function handler as default through file path

``` 
functions:
  hello:
    handler: ./src/hello.js
```

## Considerations

Before implementing this, we should think through the implications of this for future additions or changes regarding function handlers.

**Comment by sorenbs** [comment]
What is the use case for 1) if we implement 2) ?

**Comment by kbrandwijk** [comment]
I would focus on not needing to manually add/edit to the graphcool.yml file, by exposing the proper generator functions from the cli. Then, it doesn't really matter how this file is structured.

**Comment by sorenbs** [comment]
I think it is still a nice place to get an overview of your project. Especially if you get into the habit of using modules to break down the functionality into smaller self contained pieces. 

I still have nightmares of editing ASP.NET project files by hand :-D

**Comment by kbrandwijk** [comment]
1 word: tooling.

**Comment by sorenbs** [comment]
1) is implemented and released.

2) might conflict with future handler types, so that is left out for now.

**Comment by marktani** [comment]
Just noticed that this shortcut doesn't work when you need to use `environment` variables:

```
functions:
  sendEmail:
    handler:
      code:
        src: ./src/sendEmail.js
        environment:
          MAILGUN_API_KEY: ${env:MAILGUN_API_KEY}
          MAILGUN_DOMAIN: ${env:MAILGUN_DOMAIN}
```

@timsuchanek @sorenbs what do you think about that?
