### ISSUE TITLE
Add environment variable support to functions

### ISSUE THREAD

**Issue by sorenbs** [graphcool/graphcool#548]
Env variables can be added to a function with this syntax:

```
functions:
  myFunction:
    handler:
      code:
        src: ./code/myFunction.js
        environment:
          SECRET: ${env:ENV_SECRET}
```

**Comment by marktani** [comment]
How can they be used in a function?

**Comment by timsuchanek** [comment]
They will be available as an environment variable in node like this: `${process.env.SECRET}`

**Comment by kbrandwijk** [comment]
Not as a context variable?

**Comment by marktani** [comment]
That's a good point! I actually prefer the `context` because it offers a better experience across all function handlers. I don't see the `process.env` approach working with webhooks.

Related to https://github.com/graphcool/graphcool/issues/229 and https://github.com/graphcool/graphcool/issues/219.

**Comment by kbrandwijk** [comment]
Any news on this?

**Comment by marktani** [comment]
For now, you can define environment variables for managed funtions in the `graphcool.yml` file with the new CLI version, for example here: https://github.com/graphcool/modules/blob/master/authentication/github/graphcool.yml#L10-L12

For webhooks, you will need to configure the env vars at the respective webhook provider, which is actually the norm. We will look into a better integration with external function providers, but this is our current approach.

After having used the `process.env` approach, I have to say it works quite nice. It's a joy to use 🙂

**Comment by kbrandwijk** [comment]
> That's a good point! I actually prefer the context because it offers a better experience across all function handlers.

You can't win 'm all... Anyways, are the variables replaced during deployment, or actually added to process.env when running the function?

**Comment by Alex-Mann** [comment]
FWIW, I have been using [serverless](https://serverless.com/) for a few of my projects and they support importing of files in their serverless.yml.

If we were able to do this with `graphcool.yml` (you may already be able to, but I haven't checked) we could import a file called `env.yml` into the server environment as well as the `graphcool.yml`.

In the `serverless.yml`, this looks like:
```
custom:
  stage: "${opt:stage, self:provider.stage}"
  myTable: "${self:custom.stage}-my-table"

provider:
  environment: ${file(env.yml):${self:custom.stage}}

resources:
  Resources:
    MyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.myTable}
```
The `env.yml` looks like:
```
dev:
  MY_TABLE: "${self:custom.myTable}"
  API_KEY: "Development API key"

prod:
  MY_TABLE: "${self:custom.myTable}"
  API_KEY: "Production API key"
```

[This](https://forum.serverless.com/t/serverless-1-2-setting-environment-variables-and-nested-variables/861/6) thread gives a more complete discussion of the topic.
