### ISSUE TITLE
Allow setting environment-specific webhook URLs within the project definition file

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#661]
<a href="https://github.com/Merott"><img src="https://avatars3.githubusercontent.com/u/1757708?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Merott](https://github.com/Merott)**
_Saturday Sep 16, 2017 at 00:31 GMT_
_Originally opened as https://github.com/graphcool/cli/issues/249_

----

The `graphcool.yml` project definition file allows us to specify webhook handlers under function definitions. However, when working with multiple environments, the webhook URL may need to be different depending the environment. Such use case isn't currently possible with the project definition file as far as I can tell.

One suggestion would be to allow the `url` to be a dictionary of values:

```yml
functions:
  webhook-function:
    handler:
      webhook:
        url:
          dev: https://dev.example.com/webhook
          prod: https://prod.example.com/webhook
        headers:
          Content-Type: application/json
    type: subscription
    query: ./query.graphql
```

**EDIT:** I just came to realise that _theoretically_ I should be able to use a variable within the url, which would meet my need. However, looks like something isn't working because I get an error that the URL is invalid, like this:

```
Function with name 'xyz' has invalid url: 'https://${env:WEBTASK_CONTAINER}.run.webtask.io/update-map-reset-status':
```

Looks like something's gone wrong with expanding the variable.

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Saturday Sep 16, 2017 at 08:42 GMT_

----

I think using a environment variable (preferably for the entire url) in the .graphcoolrc file would be better than duplicating the environment names in the project file. There should be a single entry in the project file.

**Comment by schickling** [comment]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [timsuchanek](https://github.com/timsuchanek)**
_Saturday Sep 16, 2017 at 09:19 GMT_

----

Thanks for bringing this up @Merott !
I also think that it should be able to define that per environment in the `.graphcoolrc` file.
What we're already supporting in the latest beta:
```yaml
functions:
  webhook-function:
    handler:
      webhook:
        url: ${env:WEBHOOK_URL}
```

Defining that per environment would look like this in the `.graphcoolrc`:
```yaml
default: dev
environments:
  dev:
    projectId: cj7n3mp0f0000rayvphelgz7d
    envVars:
      WEBHOOK_URL: https://dev.example.com/webhook
  prod:
    projectId: cj7n3ob1y0001rayvdhegkcu2
    envVars:
      WEBHOOK_URL: https://prod.example.com/webhook
```
What do you think of that @Merott & @kbrandwijk ?

We have to fix the yaml validation for the interpolation, creating a separate issue for that

**Comment by schickling** [comment]
<a href="https://github.com/Merott"><img src="https://avatars3.githubusercontent.com/u/1757708?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Merott](https://github.com/Merott)**
_Saturday Sep 16, 2017 at 09:53 GMT_

----

I think using environment variables makes more sense too, but not for the entire URL, because that wouldn't be very reusable. If we had to specify the full URL in the environment variable, I'd have to create an environment variable for every webhook URL, which defeats the point. Instead, I should be able to create different URLs, like `https://${env:WEBTASK_CONTAINER}.run.webtask.io/webhook-one` and `https://${env:WEBTASK_CONTAINER}.run.webtask.io/webhook-two`, using only one variable per environment.

**Comment by schickling** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Saturday Sep 16, 2017 at 10:15 GMT_

----

That makes me think of something else. Does reusing environment variables in the .graphcoolrc file work? 

```
default: dev
environments:
  dev:
    projectId: cj7n3mp0f0000rayvphelgz7d
    envVars:
      API_KEY: abcde
      WEBHOOK_URL: https://dev.example.com/webhook?key=${env:API_KEY}
  prod:
    projectId: cj7n3ob1y0001rayvdhegkcu2
    envVars:
      API_KEY: hijkl
      WEBHOOK_URL: https://prod.example.com/webhook?key=${env:API_KEY}
```

**Comment by schickling** [comment]
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [timsuchanek](https://github.com/timsuchanek)**
_Thursday Sep 21, 2017 at 13:49 GMT_

----

We talked about this internally and concluded, that for now we want to leave the `.graphcoolrc` file like it is.
We want to keep it clean at the moment and rather rethink it anyways, as the current approach with the `cuid` project ids isn't a great experience from the CLI perspective.

Instead, for your use-case @Merott:
A "new" proposal is to go for the `opts` feature that serverless has included in their CLI: https://serverless.com/framework/docs/providers/aws/guide/variables#referencing-cli-options

That means you can inject CLI options and they would be available with `${opt:option-name}`.

In the special case of the `env` option, the CLI would inject the `default` env in there, if it's not provided

That would mean you still only have to execute
```sh
graphcool deploy
```
and this would be possible:
```yaml
functions:
  webhook-function:
    handler:
      webhook:
        url: https://${opt:env}.example.com/webhook
        headers:
          Content-Type: application/json
    type: subscription
    query: ./query.graphql
```

You then also could say
```sh
graphcool deploy --branch-name $BRANCH_NAME
export MY_ENV_DEV=123
export MY_ENV_MASTER=1234
```

```yaml
functions:
  webhook-function:
    handler:
      webhook:
        url: https://${env:MY_ENV_${opt:branch-name}}.example.com/webhook
        headers:
          Content-Type: application/json
    type: subscription
    query: ./query.graphql
```

Or
```sh
graphcool deploy --custom-path dev_url
```

```yaml
custom:
  dev_url: https://dev.example.com/webhook
  prod_url: https://prod.example.com/webhook
functions:
  webhook-function:
    handler:
      webhook:
        url: ${self:custom.${opt:custom-path}}
        headers:
          Content-Type: application/json
    type: subscription
    query: ./query.graphql
```

What do you think about these options?
Same for @kbrandwijk , do you think this approach is powerful enough for what you need?

**Comment by schickling** [comment]
<a href="https://github.com/Merott"><img src="https://avatars3.githubusercontent.com/u/1757708?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Merott](https://github.com/Merott)**
_Thursday Sep 21, 2017 at 14:03 GMT_

----

I don't intend to pass my variable through the CLI, because I find it cumbersome, especially if it's long and hard to remember. So, I think that means I wouldn't use `opts` for my webhook URLs, but I can see how it might be useful in some situations.

I only expect to be able to do this:

```yml
functions:
  webhook-function:
    handler:
      webhook:
        url: "https://${env:WEBTASK_CONTAINER}.run.webtask.io/update-map-reset-status"
        headers:
          Content-Type: application/json
```

So, I only need to set environment variables somewhere. If Graphcool CLI doesn't provide an option for it, that's fine, I can set the variables some other way and make the above work as long as Graphcool's validation is fixed.
