### ISSUE TITLE
Use `Content-Type: application/json` as default header for webhooks when no headers provided

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#698]
In the aim for "sensible defaults" and given that mostly all use cases of webhooks as function handlers require the `Content-Type: application/json` header, I suggest this header value is used by default.

This makes the following snippets effectively the same:

```yml
# explicit
functions:
  hello-world:
    type: resolver
    handler:
      webhook:
        url: https://my-webhook.com
        headers:
          Content-Type: application/json

# as url subobject (headers implicit)
functions:
  hello-world:
    type: resolver
    handler:
      webhook:
        url: https://my-webhook.com

# webhook shortnotation (headers implicit)
functions:
  hello-world:
    type: resolver
    handler:
      webhook: https://my-webhook.com
```

To explicitly **not** send any headers, use the following notation:

```yml
# no headers
functions:
  hello-world:
    type: resolver
    handler:
      webhook:
        url: https://my-webhook.com
        headers: {}
```
