### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by timsuchanek** [graphcool/graphcool#720]
## Introduction
As mentioned in #719 and #605 the current concept of modules is not fulfilling what it's promising, also the responsibilities and boundaries of a module are not clear.
The vision is, that we definitely want to have a nice `packages`, `modules` or `plugins` system, however you might call it.

The requirement you have to such a reusable collection of code and definitions is:
- Versioning, which allows updates
- Reusability without touching the code

Both are currently not the case with modules. So the idea of this proposal is to have a more "honest", short-term approach, that doesn't promote something it doesn't hold but helps to put together code, that you want to use in your project, like authentication integrations.

Later, when we have a better understanding of all this, we want to implement a solution that fits the requirements.

Until then, the proposal is to **disable modules**

## Templates
The idea of a template is, that it is basically a collection of code, that you still have to add to your project manually. In other words, copy-pasting code from a GitHub repo and manually adding it to the `graphcool.yml` would be the same as "adding a template".
This may sound like a step backward from modules, but it fosters the understanding of developers of what is actually going on in the code they are pulling into the project.

With having to manually add it to the project, you're forced to grapple with the code and automatically get a better understanding of how pieces are put together.

## CLI Command
In order to make "copy-pasting" easier, the CLI would still expose a command to gather code from github.

The current `modules add` command would be renamed to `add-template`:

```bash
gc add-template graphcool/templates/authentication/email-password
```

### graphcool.yml

A template still just has a `graphcool.yml`, but the content of this file will be added to the main project, as comments. Concretely it will look like this:

`github.com/graphcool/templates/authentication/email-password/graphcool.yml`
```yaml
# GraphQL types
types: ./types.graphql

# functions
functions:

  signup:
    type: resolver
    schema: src/signup.graphql
    handler:
      code: src/signup.js

  authenticate:
    type: resolver
    schema: src/authenticate.graphql
    handler:
      code: src/authenticate.js

  loggedInUser:
    type: resolver
    schema: src/loggedInUser.graphql
    handler:
      code: src/loggedInUser.js

# Permanent Auth Token / Root Tokens
rootTokens:
  - signup
  - authenticate
  - loggedInUser
```

Will be added to the main `graphcool.yml` like this:
```yaml
functions:
# uncomment to activate the `email-password` template:
#
#  signup:
#    type: resolver
#    schema: src/email-password/signup.graphql
#    handler:
#      code: src/email-password/signup.js
#
#  authenticate:
#    type: resolver
#    schema: src/email-password/authenticate.graphql
#    handler:
#      code: src/email-password/authenticate.js
#
#  loggedInUser:
#    type: resolver
#    schema: src/email-password/loggedInUser.graphql
#    handler:
#      code: src/email-password/loggedInUser.js

  current-function:
    type: resolver
    schema: src/hello.graphql
    handler:
      code: src/hello.js
    

rootTokens:
# uncomment to activate the `email-password` template
#
#  - signup
#  - authenticate
#  - loggedInUser
```

The code of a function will be added to `src/TEMPLATE_NAME`.
If there are naming conflicts (function name, root token name, file name) - the template installation will gracefully be stopped and an error will be printed.

The comments are all added **inline**. That means `functions` are added where current `functions` are defined etc. If the top level doesn't exist yet, it will be appended to the `graphcool.yml`.

If the top-level type like `functions` already exists, the out-commented new functions will be **prepended** to the list of functions, because it's hard to know where a definition stops, like in this example:
```yaml
functions:
  hello:
    code:
      src: ./hello.js
#   hello2:
#    code:
#      src: ./hello.js
#permissions:
#  - operation: User.read
```

### types.graphql

The `types.graphql` file will be adjusted like this:
1. If there us no user type yet:
```yaml
# uncomment to enable the `email-password` template:
# type User implements Node {
#  id: ID! @isUnique
#  email: String @isUnique
#  password: String
# }
```

2. If there already is a `User` type:
```yaml
type User implements Node {
  id: ID! @isUnique
  currentField: String!

# uncomment to enable the `email-password` template:
#  email: String @isUnique
#  password: String
}
```

This is basically flattening the concept former known as modules to a more transparent, less-magic concept called templates.
