### ISSUE TITLE
CLI updates permission even if it was not modified

### ISSUE THREAD

**Issue by l-catallo** [graphcool/graphcool#773]
The CLI keeps replacing the permission queries on the targets even if no change was made to the sources.

Issuing a `graphcool diff` just after a deploy gives me this:
```
Your project xxxxxxxxxxxxxxx of env default has the following changes:

Model Permissions

  User
   - A permission for the operation `READ` is deleted.
   - A permission for the operation `UPDATE` is deleted.
   + A permission for the operation `READ` is created.
   + A permission for the operation `UPDATE` is created.
```

Version info: `graphcool/0.7.0-beta.5 (linux-x64) node-v8.6.0`

**Comment by marktani** [comment]
Does that still happen when you do

```sh
graphcool deploy --force
graphcool diff
```
?

What's the current and the previous state of permissions in `graphcool.yml`?

**Comment by l-catallo** [comment]
Using `--force` gives the same result.

This is the permissions configuration.
```
- operation: User.read
  authenticated: true
  query: ./permissions/authIsUserOwner.graphql
- operation: User.update
  authenticated: true
  query: ./permissions/authIsUserOwner.graphql
  fields:
  - createdAt
  - familyName
  - givenName
  - id
  - name
  - picture
  - updatedAt
```
There was no permissions set on the User type before.
