### ISSUE TITLE
Error when deploying operationBefore or operationAfter hooks

### ISSUE THREAD

**Issue by richardkall** [graphcool/graphcool#818]
**What is the current behavior?**
Error when deploying: 

```
There are issues with the new service definition:

  Global
    ✖ unhandled error: File with path 'src/validateEmail.js' does not exist
```
**Please share the relevant part of your project (GraphQL schema, functions, permissions, ...) for easier reproduction**

Functions part of `graphcool.yml`:
```
functions:
  hello:
    handler:
      code: src/hello.js
    type: resolver
    schema: src/hello.graphql
  validateEmail:
    type: operationBefore
    operation: User.create
    handler:
      code: src/validateEmail.js
```

Reproducible in this minimal sample project:
https://github.com/richardkall/graphcool-hook-issue

---
Using `graphcool/0.7.0 (darwin-x64) node-v8.5.0`
