### ISSUE TITLE
Improve "Please supply a valid model. Reason: No model with name: User found."

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#829]
`types.graphql`:

```
type Subscriber @model {
  id: ID! @isUnique
  name: String!
}
```

`graphcool.yml`:

```
types: ./types.graphql

functions:
  validateEmail:
    type: operationBefore
    operation: User.create
    handler:
      code: src/validateEmail.js
```

Deploying returns the error message

> Please supply a valid model. Reason: No model with name: User found.

The error message should include the function name and type, something like this:

> Error in operationBefore function 'validate Email': No model with name 'User' found. Please supply a valid model.
