### ISSUE TITLE
fs.pathExistsSync is not a function

### ISSUE THREAD

**Issue by lastmjs** [graphcool/graphcool#875]
When I run `graphcool deploy` I get the following error in the terminal:

```
fs.pathExistsSync is not a function
```

My graphcool.yml has the following format for functions:

```
functions:
    assignment-lti-launch:
        handler:
            code:
                src: ./functions/assignment-lti-launch/assignment-lti-launch.ts
                environment:
                    PRENDUS_LTI_SECRET: ${env:PRENDUS_LTI_SECRET}
        type: resolver
        schema: ./functions/assignment-lti-launch/assignment-lti-launch.graphql
```

When I deploy with the functions defined as above, I get the error. When I remove the functions section, everything deploys fine
